version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: demo_app_backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    environment:
      - MODEL_PATH=/models/svc_pipeline.pkl
    networks:
      - demo-network

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: demo_app_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app/data:/app/data
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
